### ISSUE TITLE
Be able to show longer time than 2 days

### ISSUE THREAD

**Issue by godspeedelbow** [calibreapp/discuss#28]
Seeing the trend over 2 days is rather irrelevant for our product. I'd like to be able to see the trend over weeks or months

**Comment by benschwarz** [comment]
@godspeedelbow What you've uncovered is a pretty confusing piece of UI (thanks!) — If you have less than 7 days of data, there is no date range filter.

After you've got more than 7 days of data, you'll see something like this
<img width="1009" alt="screen shot 2015-10-21 at 2 18 38 pm" src="https://cloud.githubusercontent.com/assets/924/10636240/b703b2da-77fe-11e5-8a9c-7c7c82d3bcfd.png">

The dropdown that allows you to filter for the last 7, 30, 60 or 90 days.

In future, I'd like to make the filter a range, so that you have more granularity on what you're shown, but I think the first step is to *always show the dropdown*, rather than the confusing "last 2 days" label that you're probably seeing now: 

<img width="1001" alt="screen shot 2015-10-21 at 2 23 23 pm" src="https://cloud.githubusercontent.com/assets/924/10636316/68103c10-77ff-11e5-8942-fbd06dd3b179.png">

Thanks again for bringing this to my attention @godspeedelbow, this really helps — I'll make some changes in the next release.

**Comment by godspeedelbow** [comment]
oh haha, yes, that's pretty confusing. always showing the drop down seems like the way to go! great :) 

btw. thanks for quick response, I'll add some more issues

**Comment by benschwarz** [comment]
> I'll add some more issues

Please do! If theres anything you'd prefer to keep private, please drop an email to hello or ben @calibreapp.com 🐳

**Comment by benschwarz** [comment]
@godspeedelbow Now the dropdown is always shown (Deployed!)
